export const DUMMY_ACTION = 'DUMMY_ACTION';
export const FETCH_CONFIGURATION = 'FETCH_CONFIGURATION';
export const FETCH_CONFIGURATION_SUCCESS = 'FETCH_CONFIGURATION_SUCCESS';
export const FETCH_CONFIGURATION_FAILED = 'FETCH_CONFIGURATION_FAILED';

export const HANDLE_ERROR_API = 'HANDLE_ERROR_API';
export const HIDE_MODAL_HANDLE_ERROR_API = 'HIDE_MODAL_HANDLE_ERROR_API';

export const VALIDATION_SAID = 'VALIDATION_SAID';
export const VALIDATION_SAID_SUCCESS = 'VALIDATION_SAID_SUCCESS';
export const VALIDATION_SAID_FAILED = 'VALIDATION_SAID_FAILED';

export const VALIDATE_OTP = 'VALIDATE_OTP';
export const VALIDATE_OTP_SUCCESS = 'VALIDATE_OTP_SUCCESS';
export const VALIDATE_OTP_FAILED = 'VALIDATE_OTP_FAILED';
